version: 1
jobs:
  build:
    docker:
    - image: cirrusci/flutter
    steps:
    - checkout
    - run: ./example flutter doctor
    - run: ./example flutter test
    - run: ./example flutter -v build apk
