version: 2
jobs:
  build:
    working_directory: ~/example
    docker:
    - image: cirrusci/flutter
    steps:
    - checkout:
        path: ~/example
    - run: flutter doctor
    - run: flutter -v build apk